[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.7"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.37"}
pydantic-settings = "^2.7.1"
uvicorn = {extras = ["standart"], version = "^0.34.0"}
asyncpg = "^0.30.0"
alembic = "^1.14.1"
